version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis_db
      REDIS_PORT: 6379
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - redis_db
      - postgres_db
  redis_db:
    image: redis:latest
    volumes:
      - redis-data:/data
  postgres_db:
    image: postgres:latest
    environment:
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:  # Optional volume for Redis data persistence
  postgres-data:  # Optional volume for PostgreSQL data persistence